### ISSUE TITLE
I generate 100 thumbnails that time code is stuck

### ISSUE THREAD

**Issue by ex-mayur-edx** [Rajesh-Royal/vThumb.js#2]
I generate 100 thumbnails that time code is stuck,

Please Provide Validation in 
Enter number of thumbnails to generate input filed,

**Comment by ex-rajesh-edx** [comment]
@mayur-edx Thanks. Its a good first issue. Please create a PR of bugfix I will merge It, or I will fix it soon in next releases.

**Comment by Rajesh-Royal** [comment]
Fixed in #4
